# Generated by Django 4.0.3 on 2022-05-10 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_remove_user_balance_remove_user_email_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
        migrations.AddField(
            model_name='customermodel',
            name='VIP_status',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='balance',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
