# Generated by Django 4.0.3 on 2022-05-11 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_ordermodel_home_delivery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customermodel',
            name='delivery_free',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customermodel',
            name='orders_count',
            field=models.IntegerField(default=0),
        ),
    ]
