# Generated by Django 4.0.3 on 2022-05-13 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0013_remove_customermodel_delivery_free_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('street', models.CharField(blank=True, max_length=50)),
                ('city', models.CharField(blank=True, max_length=50)),
                ('state', models.CharField(blank=True, max_length=15)),
                ('zip_code', models.IntegerField(blank=True, null=True)),
                ('warnings', models.IntegerField(blank=True, null=True)),
                ('orders_count', models.IntegerField(default=0)),
                ('order_email', models.CharField(max_length=50)),
                ('bidding_price', models.IntegerField(blank=True)),
            ],
        ),
    ]
