# Generated by Django 4.0.3 on 2022-05-14 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0014_drivermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiddingsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('order_id', models.IntegerField()),
                ('driver_email', models.CharField(max_length=50)),
                ('delivery_price', models.IntegerField(blank=True)),
            ],
        ),
    ]
