# Generated by Django 4.0.3 on 2022-05-15 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0016_alter_biddingsmodel_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='order_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
