# Generated by Django 4.0.3 on 2022-05-15 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0018_alter_biddingsmodel_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='driver_email',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
