# Generated by Django 4.0.3 on 2022-05-15 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0019_ordermodel_driver_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='biddingsmodel',
            name='assigned',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
