# Generated by Django 4.0.3 on 2022-05-15 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0021_biddingsmodel_customer_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='biddingsmodel',
            name='customer_receipt',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='biddingsmodel',
            name='delivery_price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
