# Generated by Django 4.0.3 on 2022-05-15 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0022_biddingsmodel_customer_receipt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biddingsmodel',
            name='delivery_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
