# Generated by Django 4.0.3 on 2022-05-16 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0023_alter_biddingsmodel_delivery_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermodel',
            name='warnings',
            field=models.IntegerField(default=0),
        ),
    ]
