# Generated by Django 4.0.3 on 2022-05-16 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0024_alter_customermodel_warnings'),
    ]

    operations = [
        migrations.AddField(
            model_name='customermodel',
            name='blacklist',
            field=models.BooleanField(default=True),
        ),
    ]
