# Generated by Django 4.0.3 on 2022-05-16 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0025_customermodel_blacklist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermodel',
            name='blacklist',
            field=models.BooleanField(default=False),
        ),
    ]
